### ISSUE TITLE
read.tree not working

### ISSUE THREAD

**Issue by Boussau** [damiendevienne/phylter#2]
Apparently, ape is not loaded when loading phylter, so that read.tree does not work.

**Comment by aursiber** [comment]
Only some `ape` functions are imported when `phylter` is loaded. `read.tree` is not one of them (because it is never used into the `phylter` package). You need to load `ape` in your R session if you want to call the function `read.tree`.

**Comment by Boussau** [comment]
Thanks, I see. Perhaps you could add some explanations in the "Usage" part whose first command is read.tree?

**Comment by aursiber** [comment]
ok. indeed, it will be clearer.
