### ISSUE TITLE
ERROR: several dependecis failed (not available for package ‘phylter’)

### ISSUE THREAD

**Issue by Ofsm** [damiendevienne/phylter#3]
Hi, I'm having an issue with the installation process. I'm using Rstudio in an Ubuntu 18.04 machine

I used the command, remotes::install_github("damiendevienne/phylter")

> remotes::install_github("damiendevienne/phylter")
Downloading GitHub repo damiendevienne/phylter@HEAD
Installing 3 packages: RcppGSL, RcppZiggurat, Rfast
Installing packages into ‘/home/oscarsaenz/R/x86_64-pc-linux-gnu-library/4.2’
(as ‘lib’ is unspecified)

* installing *source* package ‘RcppGSL’ ...
** package ‘RcppGSL’ successfully unpacked and MD5 sums checked
** using staged installation
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking for gsl-config... no
configure: error: gsl-config not found, is GSL installed?
ERROR: configuration failed for package ‘RcppGSL’
* removing ‘/home/oscarsaenz/R/x86_64-pc-linux-gnu-library/4.2/RcppGSL’
ERROR: dependency ‘RcppGSL’ is not available for package ‘RcppZiggurat’
* removing ‘/home/oscarsaenz/R/x86_64-pc-linux-gnu-library/4.2/RcppZiggurat’
ERROR: dependency ‘RcppZiggurat’ is not available for package ‘Rfast’
* removing ‘/home/oscarsaenz/R/x86_64-pc-linux-gnu-library/4.2/Rfast’

The downloaded source packages are in
	‘/tmp/Rtmp7cPBeo/downloaded_packages’
Running `R CMD build`...
* checking for file ‘/tmp/Rtmp7cPBeo/remotes490844613928/damiendevienne-phylter-c0f529b/DESCRIPTION’ ... OK
* preparing ‘phylter’:
* checking DESCRIPTION meta-information ... OK
* checking for LF line-endings in source and make files and shell scripts
* checking for empty or unneeded directories
* building ‘phylter_0.9.3.tar.gz’
Installing package into ‘/home/oscarsaenz/R/x86_64-pc-linux-gnu-library/4.2’
(as ‘lib’ is unspecified)
ERROR: dependency ‘Rfast’ is not available for package ‘phylter’
* removing ‘/home/oscarsaenz/R/x86_64-pc-linux-gnu-library/4.2/phylter’
Warning messages:
1: In i.p(...) :
  installation of package ‘RcppGSL’ had non-zero exit status
2: In i.p(...) :
  installation of package ‘RcppZiggurat’ had non-zero exit status
3: In i.p(...) : installation of package ‘Rfast’ had non-zero exit status
4: In i.p(...) :
  installation of package ‘/tmp/Rtmp7cPBeo/file49082853967e/phylter_0.9.3.tar.gz’ had non-zero exit status
> library("phylter")
Error in library("phylter") : there is no package called ‘phylter’

Thanks you very much for the help!

Os.

**Comment by damiendevienne** [comment]
Hello, 
Apparently you are missing the libgsl library. Can you open a terminal and then type
sudo apt install libgsl-dev

after that you can try to reinstall phylter and see what happens. 
Tell me!

**Comment by damiendevienne** [comment]
Seems to be solved with the advice given above.
