### ISSUE TITLE
possible usage for identifying outliers in gene tree

### ISSUE THREAD

**Issue by yangliu-szu** [damiendevienne/phylter#6]
Hi,

I am wondering if I can use phylter to filter out outliers in a gene tree. For instance, the input tree for phylter is a bootstrapped tree file that contains e.g., 1000 ultrafast bootstraps from IQtree. I do get some results from my data, however, I am not sure if such usage is valid or not.

Bests,
Yang

**Comment by damiendevienne** [comment]
Well, technically PhylteR can be used for this, as it 'simply' compares trees and identifies outliers. 
For instance, if one tip is very "volatile" (it moves around in the bootstrap replicates), you can expect this species to be very often detected as outlier. And so decide to remove it for further analysis.

Hope that helps!
